version: 2.1


orbs:
  codecov: codecov/codecov@1.1.1


jobs:
  build:
    resource_class: medium
    docker:
      - image: cimg/base:stable-20.04
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Setup buildx
          command: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run:
          name: Build
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled

            version=$(git describe)
            docker_image_tag="logreposit/lacrosse-tx-reader-service:${version}"
            echo "Building docker image ${docker_image_tag} ..."

            echo ${LOGREPOSIT_DOCKERHUB_PASSWORD} | docker login -u ${LOGREPOSIT_DOCKERHUB_USERNAME} --password-stdin

            docker buildx build \
              --platform linux/arm/v7 \
              --tag ${docker_image_tag} \
              --push .

            #docker buildx build \
            # --platform linux/arm/v7,linux/arm64/v8,linux/amd64 \
            # --tag ${docker_image_tag} \
            # --push .

            echo "Successfully built image ${docker_image_tag}"
      - run:
          name: Saving docker image
          command: |
            version=$(git describe)
            docker_image_tag="logreposit/lacrosse-tx-reader-service:${version}"
            mkdir ~/docker-images/
            docker save ${docker_image_tag} > ~/docker-images/app.tar
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - project/*
            - docker-images/*


workflows:
  base-workflow:
    jobs:
      - build:
          context: logreposit
